server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # SPA Angular: rutas como /catalogo o /admin van a index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caché para assets con hash en el nombre
    location ~* \.(?:js|css|webp|svg|ico|woff2?)$ {
        try_files $uri =404;
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
}
